"""
Generalized MCR-ALS analysis tools packaging SpectroChemPy functionality
The SpectroChemPy project is described here: https://www.spectrochempy.fr/

Travert Arnaud, Fernandez Christian (2026). SpectroChemPy, a framework for processing, 
analyzing and modeling spectroscopic data for chemistry with Python (version 0.9.4.dev74). 
Zenodo, DOI: 10.5281/zenodo.3823841 URL: https://www.spectrochempy.fr

Features:
- loadAndPackageData: Handles import of .csv and .xlsx (via pandas), generates a SpectroChemPy NDDataset object.
- runPCA: PCA component visualization.
- runMCR: Carries out the MCR-ALS analysis and plots results.
"""

import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.cm as cm
from matplotlib.lines import Line2D
import spectrochempy as scp

# =============================================================================
# 1. LOAD DATA AND GENERATE SpectroChemPy's NDDataset OBJECT
# =============================================================================
def loadAndPackageData(filePath, concList, titrantName, concUnit, 
                       spectralAxisName="Wavelength", spectralUnit="nm", 
                       spectraType="Absorbance", sheetName="Raw",
                       wlStart=None, wlEnd=None, 
                       concStart=None, concEnd=None):
    """
    Loads titration data from CSV or Excel file and packages it into a SpectroChemPy NDDataset object.
    Issues a warning if the file extension is not explicitly .csv, .xlsx, or .xls.
    For Excel files, it assumes by default that the raw data is placed in a tab named "Raw".
    Gracefully handles missing Excel tabs by listing available options.
    Optionally slices the data using native SpectroChemPy coordinate slicing 
    to only include the region between wlStart and wlEnd.
    """
    
    # 1. Check file extensions explicitly and warn if unrecognized
    filePathStr = str(filePath).lower()
    
    if filePathStr.endswith(('.xlsx', '.xls')):
        xls = pd.ExcelFile(filePath)
        availableTabs = xls.sheet_names
        
        if isinstance(sheetName, str) and sheetName not in availableTabs:
            raise ValueError(
                f"\nError: The requested tab '{sheetName}' does not exist in '{filePath}'. "
                f"\nAvailable tabs are: {availableTabs}"
            )
        elif isinstance(sheetName, int) and (sheetName < 0 or sheetName >= len(availableTabs)):
            raise ValueError(
                f"\nError: The requested tab index {sheetName} is out of range for '{filePath}'. "
                f"\nAvailable tabs are: {availableTabs} (indices 0 to {len(availableTabs)-1})"
            )
            
        df = pd.read_excel(xls, sheet_name=sheetName)
        rawMatrix = df.to_numpy()
        
    elif filePathStr.endswith('.csv'):
        # Standard CSV load
        # The encoding part solves a problem with CSV files generated by Excel
        rawMatrix = np.loadtxt(filePath, delimiter=",", skiprows=1, encoding="utf-8-sig")
        
    else:
        # Fallback to CSV loading but warn the user
        warnings.warn(
            f"Expected .csv or .xlsx file extension for '{filePath}'. Defaulting to CSV parsing format.",
            UserWarning
        )
        # The encoding part solves a problem with CSV files generated by Excel
        rawMatrix = np.loadtxt(filePath, delimiter=",", skiprows=1, encoding="utf-8-sig")
    
    # 2. Extract axes and transpose the spectral matrix
    spectralAxis = rawMatrix[ :, 0 ]        
    spectraData = rawMatrix[ :, 1: ].T      
    
    # 3. Validate dimensions strictly
    numSpectra = spectraData.shape[ 0 ]
    if len(concList) != numSpectra:
        raise ValueError(
            f"\nDimension mismatch: The file contains {numSpectra} spectra, "
            f"but the concentration list has {len(concList)} items."
        )
        
    # 4. Map the data type aliases to specific SpectroChemPy titles and units
    sType = str(spectraType).lower()
    if sType in [ "absorbance", "abs" ]:
        dsTitle = "Absorbance"
        dsUnits = "absorbance"
    elif sType in [ "fluorescence", "fluo", "intensity" ]:
        dsTitle = "Intensity"
        dsUnits = "intensity"
    else:
        dsTitle = str(spectraType).capitalize()
        dsUnits = sType
        
    # 5. Build SpectroChemPy coordinates
    yCoord = scp.Coord(concList, title=f"[{titrantName}]", units=concUnit)
    xCoord = scp.Coord(spectralAxis, title=spectralAxisName, units=spectralUnit)
    
    # 6. Package into NDDataset
    dataset = scp.NDDataset(
        spectraData, 
        coordset=[ yCoord, xCoord ], 
        title=dsTitle, 
        units=dsUnits 
    )

    # 7. Apply native SpectroChemPy coordinate slicing.
    # Note: SpectroChemPy requires float values to slice by physical axes
    # (e.g., wavelength) rather than matrix indices. 
    # The inline 'is not None' checks prevent a fatal TypeError (i.e., calling float(None)) 
    # in cases where the user only provides one boundary (e.g., a start but no end).
    
    # Format wavelength boundaries (x-axis / dimension 2)
    s_start = float(wlStart) if wlStart is not None else None
    s_end = float(wlEnd) if wlEnd is not None else None
    
    # Format concentration boundaries (y-axis / dimension 1)
    c_start = float(concStart) if concStart is not None else None
    c_end = float(concEnd) if concEnd is not None else None
    
    # Apply the slice to both dimensions simultaneously: [ concentrations, wavelengths ]
    if any(var is not None for var in [s_start, s_end, c_start, c_end]):
        dataset = dataset[ c_start:c_end, s_start:s_end ]
    
    return dataset


# =============================================================================
# 2. PCA RANK ANALYSIS
# =============================================================================
def runPCA(dataset, numPCAcomponents=5, plotComponents=False, normalizeProfiles=False):
    """
    Runs PCA on the NDDataset and plots the explained variance scree plot.
    We extract the explained variance data (pcaModel.ev_ratio.data) and plot 
    it manually using Matplotlib so we can set the vertical axis to logarithmic
    scaling. Text annotations are adaptively formatted and added to the base 
    of the bars using a percentage-based axes transform.
    
    If plotComponents=True, it additionally plots the PCA concentration profiles 
    (scores) and PCA spectral profiles (loadings) side-by-side using SpectroChemPy's
    native engine routed into specific Matplotlib subplots via the `ax` parameter.
    
    If normalizeProfiles=True, the PCA concentration profiles are natively min-max 
    scaled so every component stretches exactly from 0 to 1, perfectly isolating 
    the curve shapes.
    """
    pcaModel = scp.PCA(n_components=numPCAcomponents)
    pcaModel.fit(dataset)
    
    # ---------------------------------------------------------
    # 1. Explained variance scree plot
    # ---------------------------------------------------------
    evRatio = pcaModel.ev_ratio.data
    componentIndices = np.arange(1, numPCAcomponents + 1)
    
    figPca, axPca = plt.subplots(figsize=(7, 4))
    axPca.bar(componentIndices, evRatio, color="steelblue", alpha=0.7)
    axPca.set_yscale("log")
    axPca.set_xlabel("Component index")
    axPca.set_ylabel("Explained variance (%)")
    axPca.set_xticks(componentIndices)
    
    # Add adaptive percentage text to the bottom of each bar
    # Using get_xaxis_transform() locks X to data coordinates (the bar index) 
    # and Y to axes fractions (0.0 to 1.0).
    for idx, val in zip(componentIndices, evRatio):
        
        # Adaptive rounding logic
        if val >= 1.0:
            text_str = f"{val:.1f}%"    # E.g., 98.421% -> "98.4%"
        else:
            text_str = f"{val:.1g}%"    # E.g., 0.00312% -> "0.00312%" (Uses significant figures)
            
        axPca.text(
            x=idx, 
            y=0.05,  # Exactly 5% up from the bottom edge of the chart
            s=text_str, 
            color="0.3", 
            fontweight="bold",
            rotation=90, 
            ha="center",   # Center horizontally inside the bar
            va="bottom",   # Anchor the start of the text string at the Y=0.05 mark
            transform=axPca.get_xaxis_transform()
        )

    plt.tight_layout()
    plt.show()
    
    # ---------------------------------------------------------
    # 2. PCA Scores & Loadings (Native SpectroChemPy via ax)
    # ---------------------------------------------------------
    if plotComponents:
        # Extract the NDDataset objects
        pcaScores = pcaModel.transform()
        pcaSpectra = pcaModel.components
        
        # Natively normalize the scores using Min-Max: (values - min) / (max - min)
        if normalizeProfiles:
            # dim=0 explicitly calculates min and ptp across the concentrations 
            # for each independent component curve.
            min_vals = scp.min(pcaScores, dim=0)
            ptp_vals = scp.ptp(pcaScores, dim=0)
            
            # The NDDataset inherently supports this chained mathematics and broadcasts
            # the 1D arrays correctly across the curves!
            pcaScores = (pcaScores - min_vals) / ptp_vals
        
        # Create a single standard Matplotlib figure with two independent axes
        fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))
        
        # Route the native SpectroChemPy plot for scores into the left axis (ax1)
        pcaScores.T.plot(ax=ax1)
        ax1.set_title("Concentration profiles (PCA scores)")
        
        # Route the native SpectroChemPy plot for spectra into the right axis (ax2)
        pcaSpectra.plot(ax=ax2)
        ax2.set_title("Spectral components (PCA loadings)")
        
        plt.tight_layout()
        plt.show()
        
    return pcaModel


# =============================================================================
# 3. MCR-ALS ANALYSIS
# =============================================================================
def runMCR(dataset, guessIndices, enforceInitialConc=True, 
           fixedSpecIndices=[ 0 ], decreasingIndices=None, increasingIndices=None,
           tol=0.001, maxdiv=20, maxIter=500):
    """
    Configures and runs the multicomponent resolution - alternating least 
    squares (MCR-ALS) algorithm from SpectroChemPy using extracted values
    from a provided NDDataset.
    """
    
    numComponents = len(guessIndices)
    
    # Extract data directly from the dataset
    rawData = dataset.data
    spectralAxis = dataset.x.data
    concAxis = dataset.y.data
    
    # Sensible defaults for constraints if not explicitly overridden
    if decreasingIndices is None:
        # at least the FIST component should be strictly decreasing
        decreasingIndices = [ 0 ]
    if increasingIndices is None:
        # at least the LAST component should be strictly increasing
        increasingIndices = [ numComponents - 1 ]

    # ---------------------------------------------------------
    # Initial guesses and dynamic labels&colors
    # ---------------------------------------------------------
    # Build initial guess spectrum (st0) by slicing the dataset
    st0List = [ rawData[ idx ] for idx in guessIndices ]
    st0 = np.vstack(st0List)

    # Dynamically map generalized labels and high-contrast colors
    componentLabels = [ "Initial species" ]
    componentColors = [ "blue" ]
    
    if numComponents > 2:
        cmap = cm.plasma
        colorVals = np.linspace(0.2, 0.8, numComponents - 2)
        for i in range(numComponents - 2):
            componentLabels.append(f"Intermediate {i+1}")
            componentColors.append(cmap(colorVals[ i ]))
            
    componentLabels.append("Final species")
    componentColors.append("red")

    # ---------------------------------------------------------
    # Configure MCR model
    # ---------------------------------------------------------
    # Change log_level to "INFO" to print out every iteration step
    mcrModel = scp.MCRALS(log_level="WARNING")

    # All concentrations and spectra should be non-negative
    mcrModel.nonnegConc = 'all'
    mcrModel.nonnegSpec = 'all'
    # All regression to be done with non-negative least squares
    mcrModel.solverConc = 'nnls'
    mcrModel.solverSpec = 'nnls'
    
    # Unimodality applied only to intermediates (if any exist)
    if numComponents > 2:
        mcrModel.unimodConc = list(range(1, numComponents - 1))
    else:
        mcrModel.unimodConc = [ ]

    # Apply spectral hard constraints
    mcrModel.hardSpec = fixedSpecIndices
    mcrModel.monoDecConc = decreasingIndices
    mcrModel.monoDecTol  = 1.05
    mcrModel.monoIncConc = increasingIndices
    mcrModel.monoIncTol  = 1.05
    
    # Python closure for custom initial concentration constraint
    def enforceInitialConcentration(cCurr):
        cArray = cCurr.data if hasattr(cCurr, 'data') else cCurr
        cArray[ 0, 0 ] = 1.0          
        cArray[ 0, 1: ] = 0.0         
        return cArray

    # Toggle the custom concentration constraint based on user argument
    if enforceInitialConc:
        mcrModel.hardConc = list(range(numComponents))
        mcrModel.getConc = enforceInitialConcentration

    # Iteration controls
    mcrModel.tol = tol              # default = 0.001
    mcrModel.maxdiv = maxdiv        # default = 20
    mcrModel.max_iter = maxIter     # default = 500

    # ---------------------------------------------------------
    # Run optimization
    # ---------------------------------------------------------
    mcrModel.fit(dataset, st0)

    # Check whether optimization has converged by returning the last line of the log
    # The first check with hasattr prevents an AttributeError in case the log attribute 
    # is actually missing. If an attribute is actually present, then checking
    # mcrModel.log prevents an IndexError if it's empty. 
    # Python's 'and' short-circuits, so the second check only runs if the first passes.
    if hasattr(mcrModel, 'log') and mcrModel.log:
        final_status = mcrModel.log.strip().split('\n')[-1]
        print(f"{final_status}")
    
    stResult = mcrModel.St
    cResult  = mcrModel.C
    dReconstructed = mcrModel.inverse_transform()

    # ---------------------------------------------------------
    # Setup plots
    # ---------------------------------------------------------
    xLabelSpec = f"{dataset.x.title} ({dataset.x.units})"
    yLabelSpec = dataset.title
    xLabelConc = f"{dataset.y.title} ({dataset.y.units})"

    # Plot 1: Resolved spectral components
    figSpec, axSpec = plt.subplots(figsize=(8, 5))
    for i in range(numComponents):
        axSpec.plot(spectralAxis, stResult.data[ i ], label=componentLabels[ i ], color=componentColors[ i ], linewidth=3)
    axSpec.set_xlabel(xLabelSpec)
    axSpec.set_ylabel(yLabelSpec)
    axSpec.set_title(f"MCR-ALS resolved spectra ({numComponents} components)")
    axSpec.legend()
    plt.tight_layout()
    plt.show()

    # Plot 2: Concentration profiles
    figConc, axes = plt.subplots(1, 2, figsize=(14, 5))
    xScales = ["linear", "log"]
    for ax, scale in zip(axes, xScales):
        for i in range(numComponents):
            ax.plot(concAxis, cResult.data[ :, i ], label=componentLabels[ i ], color=componentColors[ i ], linewidth=2, marker="o", markersize=4)
        ax.set_xscale(scale)
        ax.set_xlabel(xLabelConc)
        ax.set_ylabel("Relative fraction")
        ax.set_title(f"Concentration profiles ({scale} scale)")
        ax.legend()
    plt.tight_layout()
    plt.show()

    # Plot 3: Fit quality and fit residuals
    axMerit = mcrModel.plotmerit(
        X_hat=dReconstructed, nb_traces=5,
        exp_c="black", calc_c="darkorange", resid_c="0.4",
        exp_linestyle="-", calc_linestyle="-", resid_linestyle="-"
    )
    customLegend = [
        Line2D([ 0 ], [ 0 ], color="black", linestyle="-", label="experimental"),
        Line2D([ 0 ], [ 0 ], color="darkorange", linestyle="-", label="reconstructed"),
        Line2D([ 0 ], [ 0 ], color="0.4", linestyle="-", label="residuals")
    ]
    plt.legend(handles=customLegend, loc="best")
    plt.show()

    # Plot 4: Comparisons between first spectrum and first component, and last spectrum and last component
    figComp, axesComp = plt.subplots(1, 2, figsize=(14, 5))
    axesComp[ 0 ].plot(spectralAxis, rawData[ 0 ], label="First spectrum", color="black", linestyle="-", linewidth=2)
    axesComp[ 0 ].plot(spectralAxis, stResult.data[ 0 ], label=f"Resolved {componentLabels[ 0 ]}", color=componentColors[ 0 ], linestyle="--", linewidth=2)
    axesComp[ 0 ].set_xlabel(xLabelSpec)
    axesComp[ 0 ].set_ylabel(yLabelSpec)
    axesComp[ 0 ].set_title("Initial spectrum comparison")
    axesComp[ 0 ].legend()

    axesComp[ 1 ].plot(spectralAxis, rawData[ -1 ], label="Last spectrum", color="black", linestyle="-", linewidth=2)
    axesComp[ 1 ].plot(spectralAxis, stResult.data[ -1 ], label=f"Resolved {componentLabels[ -1 ]}", color=componentColors[ -1 ], linestyle="--", linewidth=2)
    axesComp[ 1 ].set_xlabel(xLabelSpec)
    axesComp[ 1 ].set_ylabel(yLabelSpec)
    axesComp[ 1 ].set_title("Final spectrum comparison")
    axesComp[ 1 ].legend()
    
    plt.tight_layout()
    plt.show()
    
    return mcrModel, stResult, cResult