(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
SetOptions[InputNotebook[],AutoGeneratedPackage->Automatic]

BeginPackage["titrationTools`"]
ClearAll[titrationExplorer]
ClearAll[titrationPrinter]
ClearAll[spectraExplorer]
ClearAll[waterfallPlot]

(* Only the functions whose usage messages are generated below are accessible outside of the package *)
(* see ?GeneralUtilities`SetUsage for the required syntax in the usage strings *)
GeneralUtilities`SetUsage[titrationExplorer,"titrationExplorer[input$] imports the Excel worksheet input$ that contains titration data and produces a row of two dynamic plots: a stack of spectra and a titration profile. The wavelength at which the titration profile is drawn is indicated by the red vertical line in the spectra plot and can be selected by clicking and dragging with the mouse. The wavelength range for the spectra plot can be adjusted using the sliders at the top.

The default behavior can be modified by specifying the following options as 'option$ name$' -> value$; multiple options can be used, separated by a comma: 
| option name | default value | action |
| --- | --- | --- |
| 'tab' | 'dilution corrected' | from which tab data should be loaded in the input$ Excel file |
| 'maxeq' | All | up to how many equivalents to plot the titration profiles |"]

GeneralUtilities`SetUsage[titrationPrinter,"titrationPrinter[input$, {lambda$1, $$, lambda$4}] imports the Excel worksheet input$ that contains titration data and produces five plots, formatted in a grid: a line plot of the stack of spectra and four titration profiles as scatter plots, each at wavelength lambda$i.

The default behavior can be modified by specifying the following options as 'option$ name$' -> value$; multiple options can be used, separated by a comma: 
| option name | default value | action |
| --- | --- | --- |
| 'tab' | 'dilution corrected' | from which tab data should be loaded in the input$ Excel file |
| 'minlambda' | 260 | lower limit of the wavelength range for the stack of spectra plot |
| 'maxlambda' | 600 | upper limit of the wavelength range for the stack of spectra plot |
| 'maxeq' | All | up to how many equivalents to plot the titration profiles |
| 'output' | Automatic | by default the plot grid is output to the screen; see other options below |
The \!\(\*StyleBox[\"output options\",FontWeight->\"Bold\"]\) are as follows:
| 'output' -> Automatic | shows output on screen |
| 'output' -> 'format$' | generates a file in the specified format$ (e.g. PDF, SVG, PNG $$) with the same name and location as input$ |
| 'output' -> {'format$', options$} | generates a file in format$ with the same name and location as input$, with the Export options specified by options$ |
| 'output' -> {'format$', output$} | generates a file in format$ at location output$ |
| 'output' -> {'format$', output$, options$} | generates a file in format$ at location output$, with the Export options specified by options$ |"]

GeneralUtilities`SetUsage[spectraExplorer,"spectraExplorer[input$] imports the Excel worksheet input$ that contains titration data and produces an animated line plot of the stack of spectra.

The default behavior can be modified by specifying the following options as 'option$ name$' -> value$; multiple options can be used, separated by a comma: 
| option name | default value | action |
| --- | --- | --- |
| 'tab' | 'dilution corrected' | from which tab data should be loaded in the input$ Excel file |
| PlotRange | {{260, 800}, {-0.05, 1.4}} | wavelength and absorbance ranges, respectively |"]

GeneralUtilities`SetUsage[waterfallPlot,"waterfallPlot[data$] plots all spectra in data$ as a 3D waterfall plot.
waterfallPlot[data$, howMany$] plots approximately howMany$ evenly subsampled spectra.
waterfallPlot[data$, howMany$, colors$] fills spectra using the given color, or a smooth gradient generated from the provided color list.
waterfallPlot[data$, howMany$, colors$, opt$ -> val$, $$] applies additional options among those accepted by ListLinePlot3D.

| Argument | Description |
| --- | --- |
| data$ | A 2D numeric array. Row 1 ignored. Column 1 = wavelengths. Other columns = one spectrum each. |
| howMany$ | Integer. Approximately how many spectra to display by uniform subsampling, omit to display all. Displayed spectra retain their original positions. |
| colors$ | A single color or a list of color directives. Single color = uniform filling. Color list = gradient filling from first to last spectrum. Default: {Blue, Red}. |

| Option | Default | Description |
| --- | --- | --- |
| PlotRange | {Full, Full, Full} | Plot range for {wavelengths$, spectrumIndex$, absorbance$}. Each can be Full, All, or an explicit {min$, max$} interval. |
| BoxRatios | {1, 4, 1} | Sets the relative lengths of the bounding box edges ({wavelengths$, spectrumIndex$, absorbance$}). |

Any option valid for ListLinePlot3D may also be supplied. Axis labels are intentionally omitted. Add them in post-processing."]


(* private section: implementation code *)
Begin["`Private`"]

(* ================= *)
(* TITRATION EXPLORER *)
(* ================= *)
Options[titrationExplorer]={"tab"->"dilution corrected","maxeq"->All};
titrationExplorer[fileName_String,OptionsPattern[]]:=
DynamicModule[
{all,equivalents,wavelengths,spectra,profiles,selectedWavelength=370,min,max},

all=Import[fileName,{"Sheets",OptionValue["tab"]}];
equivalents=Cases[all,{"equivalents",eq__}:>eq];
wavelengths=Round@all[[First@FirstPosition[all,"Wavelength"]+1;;,1]];
spectra=Map[
(* form {wavelength, absorbance} pairs for each spectrum --> *)Transpose[{wavelengths,#}]&,
Transpose@ (* spectral values --> *)all[[First@FirstPosition[all,"Wavelength"]+1;;,2;;]]
];
profiles=GroupBy[all[[First@FirstPosition[all,"Wavelength"]+1;;]],Round@*First->Rest,Flatten];

Grid[{
{
Item["Plot range:",Alignment->{Left,Scaled[1/2]}],
Control[{{min,Min@wavelengths,""},Min@wavelengths,Max@wavelengths,2,ControlType->Slider,Appearance->"Labeled",BaseStyle->FontSize->18}],
Control[{{max,Max@wavelengths,""},250,Max@wavelengths,2,ControlType->Slider,Appearance->"Labeled",BaseStyle->FontSize->18}]
},
{
EventHandler[
Dynamic@ListLinePlot[
spectra,
PlotStyle->Directive[Black,Thin],
PlotRange->{{min,max},All},PlotRangePadding->{None,{0.05,Automatic}},ImagePadding->{{50,15},{45,10}},
AspectRatio->1,ImageSize->Scaled[1/4],
Frame->True,Axes->False,FrameStyle->Directive[Black,14],
FrameLabel->(Style[#,18]&/@{"wavelength / nm","corrected absorbance / a.u."}),
PlotHighlighting->None,
Epilog->{Red,Thick,InfiniteLine[{Dynamic@selectedWavelength,0},{0,1}]}
],
"MouseDragged":>(selectedWavelength=Round[First[MousePosition["Graphics"]],2])
],
SpanFromLeft,
Dynamic@ListPlot[
Transpose@{equivalents,profiles[[Key[selectedWavelength]]]},
PlotStyle->Black,
PlotRange->{{0,OptionValue["maxeq"]},All},PlotRangePadding->{Scaled[0.05],Automatic},ImagePadding->{{65,10},{45,10}},
AspectRatio->1,ImageSize->Scaled[1/4],
Frame->True,Axes->False,FrameStyle->Directive[Black,14],
FrameLabel->(Style[#,18]&/@{"equivalents of metal ion","Abs @ "<>ToString[selectedWavelength]<>" nm"}),
PlotHighlighting->{"XNearestPoint","XLabel","XYDroplines"}
]
}
},
Frame->All
]
]


(* =============== *)
(* TITRATION PRINTER *)
(* =============== *)
Options[titrationPrinter]={"tab"->"dilution corrected","maxeq"->All,"minlambda"->260,"maxlambda"->600,"output"->Automatic};
titrationPrinter::filenotfound="The indicated file could not be found.";
titrationPrinter::listlength="Exactly four wavelengths should be specified for profile plotting. You specified `1` instead.";
titrationPrinter::WLnotfound="Some of the profile wavelengths requested `1` were not found in the input file.";

titrationPrinter[fileName_String,profilePos_?(VectorQ[#,NumberQ]&),OptionsPattern[]]:=
Module[
{all,equivalents,wavelengths,spectralData,spectraPlot,profilesData,
profilePlotter,min=OptionValue["minlambda"],max=OptionValue["maxlambda"],
profilePositions=Round[profilePos,2],
profile1,profile2,profile3,profile4,
gridOutput},

(* Check that the named input file exists and that the right number of wavelengths was specified *)
If[FileExistsQ[fileName]=!=True,Message[titrationPrinter::filenotfound];Abort[]];
If[Length[profilePos]!=4,Message[titrationPrinter::listlength,Length[profilePos]];Abort[]];

all=Import[fileName,{"Sheets",OptionValue["tab"]}];
equivalents=Cases[all,{"equivalents",eq__}:>eq];
wavelengths=Round@all[[First@FirstPosition[all,"Wavelength"]+1;;,1]];

(* Check that the speficied wavelengths are actually among those available for plotting *)
If[ContainsAll[wavelengths,profilePositions]=!=True,Message[titrationPrinter::WLnotfound,StringReplace[ToString[Complement[profilePositions,wavelengths]],{"{"->"(","}"->")"}]];Abort[]];

spectralData=Map[
(* form {wavelength, absorbance} pairs for each spectrum --> *)Transpose[{wavelengths,#}]&,
Transpose@ (* spectral values --> *)all[[First@FirstPosition[all,"Wavelength"]+1;;,2;;]]
];
profilesData=GroupBy[all[[First@FirstPosition[all,"Wavelength"]+1;;]],Round@*First->Rest,Flatten];

spectraPlot=
ListLinePlot[
spectralData,
PlotStyle->Directive[Black,Thin],
PlotRange->{{min,max},All},PlotRangePadding->{None,{0.05,Automatic}},
Frame->True,Axes->False,
FrameStyle->Directive[Black,11],
FrameTicks->{{Automatic,None},{Automatic,None}},
PlotHighlighting->None,Background->None
];

profilePlotter=
ListPlot[
Transpose[{equivalents,profilesData[#]}],
PlotStyle->Directive[Black,PointSize->0.02],
PlotRange->{{0,OptionValue["maxeq"]},All},PlotRangePadding->{Scaled[0.05],Automatic},
Frame->True,Axes->False,FrameStyle->Directive[Black,11],
FrameTicks->{{Automatic,None},{Automatic,None}},
AspectRatio->1,
PlotHighlighting->None,Background->None,
Epilog->Inset[Style[ToString@#<>" nm",14],Scaled[{0.98,0.5}],{Right,Top}]
]&;

{profile1,profile2,profile3,profile4}=profilePlotter/@profilePositions;

gridOutput=Grid[
{
{Style[FileBaseName[fileName],18,Black,Bold],SpanFromLeft,SpanFromLeft,SpanFromLeft},
{Style[Rotate["Dilution-corrected absorbance",90Degree],12,FontFamily->"Arial"],Show[spectraPlot,ImageSize->{384,176},AspectRatio->Full],SpanFromLeft,profile1},
{SpanFromAbove,Style["    wavelength / nm",12,FontFamily->"Arial"],SpanFromLeft,Style["    equivalents",12,FontFamily->"Arial"]},
{SpanFromAbove,profile2,profile3,profile4},
{SpanFromAbove,Style["    equivalents",12,FontFamily->"Arial"],SpanFromLeft,SpanFromLeft}
},
Spacings->{
(*horizontal*)
{0,0.5,0.5,0.5,0},
(*vertical*)
{0,0.5,-0.1,0.5,-0.1,0}
},
Alignment->{Center,Center},Background->None
];

iPrinter[gridOutput,OptionValue["output"],fileName]
]

ClearAll[iPrinter]
iPrinter[grid_Grid,Automatic,_]:=grid
iPrinter[grid_Grid,format_String,inputFileName_]:=Export[FileNameJoin[{DirectoryName[inputFileName],StringJoin[FileBaseName[inputFileName],".",ToLowerCase@format]}],grid,format]
iPrinter[grid_Grid,{format_String,options:OptionsPattern[Export]},inputFileName_]:=Export[FileNameJoin[{DirectoryName[inputFileName],StringJoin[FileBaseName[inputFileName],".",ToLowerCase@format]}],grid,format,options]
iPrinter[grid_Grid,{format_String,outputFileName_String,options:OptionsPattern[Export]},inputFileName_]:=Export[outputFileName,grid,format,options]


(* =============== *)
(* SPECTRA EXPLORER *)
(* =============== *)
Options[spectraExplorer]={"tab"->"dilution corrected",PlotRange->{{260,800},{-0.05,1.4}}};
spectraExplorer[fileName_String,OptionsPattern[]]:=
Module[
{frames,all,equivalents,wavelengths,spectra,profiles},

all=Import[fileName,{"Sheets",OptionValue["tab"]}];
equivalents=Cases[all,{"equivalents",eq__}:>eq];
wavelengths=Round@all[[First@FirstPosition[all,"Wavelength"]+1;;,1]];
spectra=Map[
(* form {wavelength, absorbance} pairs for each spectrum --> *)Transpose[{wavelengths,#}]&,
Transpose@ (* spectral values --> *)all[[First@FirstPosition[all,"Wavelength"]+1;;,2;;]]
];

frames=MapThread[
ListLinePlot[
#1,
PlotStyle->Black,
PlotRange->OptionValue[PlotRange],
AspectRatio->0.5,ImageSize->Full,
Frame->True,Axes->False,FrameStyle->Directive[Black,14],
FrameLabel->(Style[#,18]&/@{"wavelength / nm","corr. Abs / a.u."}),
Epilog->Inset[Style["equiv = "<>ToString@#2,18,Red],Scaled[{0.97,0.97}],Scaled[{1,1}]]
]&,
{spectra,NumberForm[#,{Infinity,2}]&/@equivalents}
];

ListAnimate[frames,AnimationRunning->False,ImageSize->Scaled[1/3]]
]

(* ============ *)
(* waterfallPlot *)
(* ============ *)
Options[waterfallPlot]={
PlotRange->{Full,Full,Full},
PlotRangePadding->{
0(*x axis (wavelengths): no padding*),
1(*y axis (spectrum number): one unit of padding (range plus/minus 1)*),
{0,Scaled[0.05]}(*absorbance (z axis): no padding at the bottom of the range, 5% padding at the top*)
},
Axes->True,AxesStyle->Directive[Black,AbsoluteThickness[1.5],FontSize->18],
BoxRatios->{1,4,1},
ImageSize->Scaled[1/3],
AxesLabel->None
};

waterfallPlot[
data_?(ArrayQ[#,2]&),
Optional[howMany_Integer?(#>1&),All],(*if specified, check that howMany is at least 2. Values of 1 or 0 are nonsensical and would also cause code to fail.*)
Optional[colors_?(Or[ColorQ[#](*a single color*),VectorQ[#,ColorQ](*a list of colors*)]&),{Blue,Red}],
options:OptionsPattern[{waterfallPlot,ListLinePlot3D}]
]:=Module[
{indexRowQ,startRow,spectra,wavelengths,every,colorList},

(*Helper function to check whether the first row in the data set is a sample index.*)
(*Function compares the numeric entries against {1, 2, 3, ...}. A tolerance of 0.5 accommodates float imprecision on import.*)(*Absorbance values would differ from a sequential integer counter by far more than 0.5.*)
indexRowQ[row_]:=With[{nums=row[[2;;]]},VectorQ[nums,NumericQ]&&Max@Abs[nums-Range@Length@nums]<0.5];

(*Expected data layout from the HP 8452A UV Vis machine and Olis software:*)
(*Row 1 contains sample indices, column 1 contains wavelengths, the remaining columns are spectra*)
(*The transpose ensures that each spectrum, originally a column, becomes a row as required by ListLinePlot3D*)
(*Skip the first row if it is a sample index row (checked by indexRowQ), otherwise keep it.*)
(*This allows the function to seamlessly accept either the raw dataset (with the index row) or a pre-trimmed dataset*)
startRow=If[indexRowQ[data[[1]]],2,1];
spectra=Transpose[data[[startRow;;,2;;]]];
wavelengths=Round@data[[startRow;;,1]];

(*The function is passed a number of spectra to plot*)
(*The default is set to All, which corresponds to a pitch of 1.*)(*  A caller could not possibly pass All as an argument because howMany is typed as an Integer in the function prototype,*)(*  so its presence signals that the argument was omitted by the caller.*)
(*If a numeric value is passed, then it calculates the pitch to give the closest achievable number:*)
every=If[howMany===All,1,Ceiling[Length[spectra]/howMany]];

(*the colors argument is either a list of colors, or a single color directive*)
(*if it's a list, the use it as is*)
(*if it's a single color, then make it into a list of two identical items, so it can be used in Blend below*)
colorList=If[Head[colors]===List,colors,{colors,colors}];

ListLinePlot3D[
spectra[[;;;;every]],

(*The y data range spans the original spectrum count even after subsampling,*)
(*so each plotted spectrum lands close to its true position along the y-axis:*)
(*e.g. with every = 3, spectra appear close to their correct original indices 1, 4, 7... rather than being compressed to 1, 2, 3...*)
DataRange->{
MinMax@wavelengths,
{1,Length@spectra}
},

(*There is no easy way to combine a color function with FillingStyle*)
(*If any filling style (e.g. opacity) is specified, then the filling colors revert to the default style instead of the ones from ColorFunction*)
(*so instead I outline the plot in black...*)
PlotStyle->Directive[Black,AbsoluteThickness[2.5]],
(*...and color the filling by hand using explicit Filling directives*)
Filling->MapThread[#1->{Axis,Blend[colorList,#2]}&,{#,Rescale[#]}&@Range[Length@spectra[[;;;;every]]]],
Lighting->AmbientLight[White],

PlotRange->OptionValue[PlotRange],
PlotRangePadding->OptionValue[PlotRangePadding],
Axes->OptionValue[Axes],AxesStyle->OptionValue[AxesStyle],AxesLabel->OptionValue[AxesLabel],
BoxRatios->OptionValue[BoxRatios],ImageSize->OptionValue[ImageSize],

(*Add any other options provided by the user, as long as they are valid ListLinePlot3D options.*)
(*Placing them last is safe: any duplicates at the end are simply ignored by the first-wins rule.*)
Sequence@@FilterRules[{options},Options@ListLinePlot3D]
]
]

End[](* end of the private portion of the package *)
EndPackage[]
